---
- name: Create an Incident in ServiceNow
  hosts: localhost
  gather_facts: false

  collections:
  - servicenow.itsm
  
  vars_files:
    - ../vars/servicenow_vars.yml
    
  tasks:
    - name: Create an incident using the ServiceNow REST API
      uri:
        url: "https://{{ snow_instance }}.service-now.com/api/now/table/incident"
        method: POST
        user: "{{ snow_username }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          short_description: "Incident created using ServiceNow API via Ansible"
          description: "This is a test incident created via Ansible"
          urgency: "3"
          impact: "3"
        return_content: yes
        status_code: 201
      register: result

    - name: Show result
      debug:
        msg: "{{ result.json.result.number }}"
