---
- name: Create an Incident in ServiceNow
  hosts: localhost
  gather_facts: false

  collections:
  - servicenow.itsm

  tasks:
    - name: Create an incident ticket
      servicenow.itsm.incident:
        instance: "{{ SN_INSTANCE }}"
        username: "{{ SN_USERNAME }}"
        password: "{{ SN_PASSWORD }}"
        state: present
        description: "Server Unreachable"
        impact: 2
        urgency: 2
      register: result

    - name: Show Incident Info
      debug:
        var: result.record