- name: Create a Problem Record
  hosts: localhost
  gather_facts: false

  collections:
  - servicenow.itsm

  vars:
   snow_instance: "dev313896"
   snow_username:  "aes.creator"
   snow_password: "wAAy0$/AsS9n"

  tasks:
    - name: Create a Problem using the ServiceNow REST API
      uri:
        url: "https://{{ snow_instance }}.service-now.com/api/now/table/problem"
        method: POST
        user: "{{ snow_username }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        headers:
          Accept: "application/json"
          Content-Type: "application/json"
        body_format: json
        body:
          name: "Test problem via Ansible"
          description: "This is a test problem created via Ansible"
        return_content: yes
        status_code: 201
      register: result

    - name: Show result
      debug:
        msg: "{{ result.json.result.number }}"