---
- name: Create an Problem using ServiceNow ITSM Collection
  hosts: localhost
  gather_facts: false

  vars_files:
    - ../vars/servicenow_vars.yml

  tasks:
    - name: Create problem via servicenow.itsm.problem module
      servicenow.itsm.problem:
        instance:
          host: "https://{{ snow_instance }}.service-now.com"
          username: "{{ snow_username }}"
          password: "{{ snow_password }}"
        
        state: new
        short_description: "This is a problem created using Ansible ITSM collection"
        description: "This is a demo problem created using ansible"
        impact: medium
        urgency: low
        other:
          user_input: notes
      register: result

    - name: Show the problem number
      debug:
        msg: "Problem created: {{ result.record.number }}"