---
- name: Create an Incident in ServiceNow
  hosts: localhost
  gather_facts: false

  collections:
  - servicenow.itsm

  #vars:
  # snow_instance: "dev313896"
  # snow_username:  "aes.creator"
  # snow_password: "wAAy0$/AsS9n"

  vars_files:
    - ../vars/servicenow_vars.yml
  tasks:
    - name: Send GET request to ServiceNow incident table
      uri:
        url: "https://{{ snow_instance }}.service-now.com/api/now/table/incident"
        method: GET
        user: "{{ snow_username }}"
        password: "{{ snow_password }}"
        force_basic_auth: yes
        return_content: yes
        status_code: 200
        headers:
          Accept: "application/json"
      register: response

    - name: Show response status and sample result
      debug:
        msg:
          - "HTTP status: {{ response.status }}"
          - "Sample record: {{ response.json.result[0] | default('No results returned') }}"

    - name: Show simplified incident numbers
      debug:
       msg: "{{ item.number }}"
      loop: "{{ response.json.result | default([]) }}"
      loop_control:
       label: "{{ item.number }}"

